kind: Service
apiVersion: v1
metadata:
  name: {{ include "koprator.fullname" . }}-nodeport
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8080
      nodePort: 31000
  selector:
    {{- include "koprator.selectorLabels" . | nindent 4 }}
